name: Dependabot
on:
  schedule:
    - cron: 0 0 * * * # Run at midnight UTC daily
  workflow_dispatch: # Allow manual triggering
  push:

permissions:
  id-token: write
  contents: write

jobs:
  update-lockfile:
    environment: nemo-ci
    runs-on: linux-amd64-cpu16
    steps:
      - name: Install Azure CLI
        run: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Azure ACR Login
        run: az acr login --name nemoci

      - name: Checkout repo
        uses: actions/checkout@v4

      # - name: Upgrade lock file
      #   run: |
      #     docker run \
      #     --rm \
      #     -v $(pwd):/workspace \
      #     -w /workspace \
      #     nemoci.azurecr.io/nemo_container_export_deploy_trtllm:main \
      #     bash -c 'uv lock --upgrade'

      - name: Upgrade lock file
        run: |
          echo test > uv.lock

      - name: Upload lock file
        uses: actions/upload-artifact@v4
        with:
          name: lock-file
          path: uv.lock

  create-pr:
    needs: [update-lockfile]
    runs-on: ubuntu-latest
    environment: main
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: Install GPG
        run: sudo apt-get install -y gnupg2

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@e89d40939c28e39f97cf32126055eeae86ba74ec
        with:
          gpg_private_key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PWD }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Download lock file
        uses: actions/download-artifact@v4
        with:
          name: lock-file

      - name: Get todays date
        id: date
        run: echo "main=$(date +%F)" | tee -a "$GITHUB_OUTPUT"

      - name: Create Bump PR
        uses: peter-evans/create-pull-request@v7
        id: create-pull-request
        with:
          branch: dependabot-${{ steps.ref.outputs.date }}-main
          base: main
          title: "chore(ğŸ¤–): Bump dependencies (${{ steps.date.outputs.main }})"
          token: ${{ secrets.PAT }}
          body: |
            ğŸš€ PR to bump dependencies.  

            ğŸ“ Please remember the following to-do's before merge: 
            - [ ] Verify the presubmit CI  

            ğŸ™ Please merge this PR only if the CI workflow completed successfully.
          commit-message: "build: uv.lock"
          committer: "Oliver KÃ¶nig <okoenig@nvidia.com>"
